version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - ENV_VAR=example
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "3"